services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dotboard
      POSTGRES_PASSWORD: dotboard
      POSTGRES_DB: dotboard
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
